### ISSUE TITLE
Fix fields initialized with empty string instead of null in seeding docs

### ISSUE THREAD

**Issue by laurensgroeneveld** [bccsa/luminary#295] opened 2024-08-15 16:57 UTC
By initializing with an empty string we can get strange behaviour like the video field showing without an actual video in it.

Check all fields, but especially these on the `content` docs:
- `audio`
- `video`
- `localisedImage`

**Comment by DirkDevelopmentFreelance** [comment] 2024-08-21 07:36
I am working on this.

**Comment by belljohan3** [comment] 2024-08-23 09:00
Hey @laurensgroeneveld !

This is actually works when we create a new post. But on the posts can come from the seeding process. The video input field keeps open.
May be the problem is not in the code ?

**Comment by laurensgroeneveld** [comment] 2024-08-23 10:11
> This is actually works when we create a new post. But on the posts can come from the seeding process. The video input field keeps open.

Aha, you're right 👍 The seeded docs have `video` initialized with an empty string as opposed to `null`. We probably want to fix that then, but then it's not really an issue otherwise.

**Comment by laurensgroeneveld** [comment] 2024-08-23 10:13
I have updated the ticket with this information. That makes this a very small fix.

**Comment by belljohan3** [comment] 2024-08-23 12:17
This is now fixed

**Closed** 2024-08-23 18:07 UTC
